### ISSUE TITLE
Interface para deletar professor

### ISSUE THREAD

**Issue by IagoCarvalho** [MPS-FGA/Avaleasy-app#11]
Feature: #4 [Manter Perfil de Professor](https://github.com/MPS-FGA/Avaleasy-app/issues/4)

Eu como professor desejo deletar meus dados da aplicação, para remover minhas informações.

Critérios de aceitação:
- [ ] Deletar dados a partir de id
- [ ] Testes
- [ ] Interface
- [ ] Endpoints da API
- [ ] Testes

**Comment by IagoCarvalho** [comment]
Débito da Sprint 01

**Comment by matheusbsilva** [comment]
Trabalhando na issue na branch 11#delete_teacher
