### ISSUE TITLE
Interface para visualizar professor

### ISSUE THREAD

**Issue by matheusbsilva** [MPS-FGA/Avaleasy-app#13]
Feature: #4 [Manter Perfil de Professor](https://github.com/MPS-FGA/Avaleasy-app/issues/4)

Eu como professor desejo visualizar meus dados na aplicação, para ter controle sobre a minha informações.

Critérios de aceitação:
- [x] Visualizar campo nome
- [x] Visualizar campo e-mail
- [x] Cada professor só tem acesso ao próprio perfil
- [ ] Testes

**Comment by lucaaas** [comment]
O protótipo não abrange os critérios de aceitação, por isso ficará diferente

**Comment by matheusbsilva** [comment]
Issue reaberta, pois foi construída de forma estática.

**Comment by matheusbsilva** [comment]
Débito da Sprint 03
