### ISSUE TITLE
Configurar folha de estilo

### ISSUE THREAD

**Issue by lucaaas** [MPS-FGA/Avaleasy-app#14]

**Comment by andre-filho** [comment]
A stylesheet é do eslint ou tipo cores e etc?

**Comment by andre-filho** [comment]
Caso sejam das cores pode dar assign pra mim e pro alexis, que eu faço o .scss do tema de cores, tipografia e etc

**Comment by alaxalves** [comment]
Eu e @andre-filho vamo pegar essa.
