### ISSUE TITLE
Criar modelo avaliação

### ISSUE THREAD

**Issue by IagoCarvalho** [MPS-FGA/Avaleasy-app#23]
Feature #6 

Eu como professor, desejo criar um modelo de avaliação para facilitar a criação de avaliações.

Critérios de Aceitação:

- [x]  Criar endpoint para criar avaliação
- [x] Campo nome do modelo
- [x] Descrição do modelo 
- [x] Quantidade de questões
- [x] Adicionar questão ao modelo
   - Questão pode ser do tipo
        - [x] Múltipla escolha
        - [x] Objetiva 
        - [x] V ou F
        - [x] TBL
   - [x] Questão deve ter pontuação

- [x] Testes

**Comment by lucaaas** [comment]
Como é feita a indicação de questões subjetivas? Eu só vi para questões VouF, objetivas, múltiplas alternativas e TBL.

**Comment by lucaaas** [comment]
Qual a diferença entre questões objetivas e de múltipla escolha?

**Comment by IagoCarvalho** [comment]
Subjetivas não estavam nos requisitos, esqueci de atualizar na issue, mas as que estão aí refletem todas as necessárias dos requisitos. Objetiva só precisa do conteúdo (title) para o modelo, múltipla escolha precisa de um conteúdo da questão, além de um conteúdo pra cada alternativa.

**Comment by lucaaas** [comment]
Ok, me convenceu :smile: :confetti_ball:
