### ISSUE TITLE
Dependências não estão sendo salvas

### ISSUE THREAD

**Issue by IagoCarvalho** [MPS-FGA/Avaleasy-app#31]
Build do Docker possui mesmo problema do repositório do backend, onde as dependências estão sendo instaladas separadas por não serem salvas.

**Comment by matheusbsilva** [comment]
@IagoCarvalho não tenho certeza se entendi perfeitamente qual o problema, mas acredito que foi o mesmo que enfrentamos no back-end. Solucionei da mesma maneira que foi solucionado no back-end, se puder revisar #37

**Comment by IagoCarvalho** [comment]
@matheusbsilva  É esse problema mesmo. nice one.
