### ISSUE TITLE
Integrar sistema de login no app

### ISSUE THREAD

**Issue by matheusbsilva** [MPS-FGA/Avaleasy-app#35]
Eu como desenvolvedor desejo integrar o sistema de login do app com o back-end para realizar a autenticação dos usuários do aplicativo.

### Critérios
- [x] Utilizar o endpoint de login do back-end: `/login`
- [x] Passar informações
  - [x] Email
  - [x] Senha
- [x] Salvar o token de autenticação para realizar as próximas requisições

**Comment by IagoCarvalho** [comment]
Incompleta devido [Issue #26](https://github.com/MPS-FGA/Avaleasy-backend/issues/26)

**Comment by IagoCarvalho** [comment]
Issue débito da Sprint 05

**Comment by matheusbsilva** [comment]
Issue congelada devido a problema descrito na  [Issue #26](https://github.com/MPS-FGA/Avaleasy-backend/issues/26). Aguardando finalização da [Issue #28](https://github.com/MPS-FGA/Avaleasy-backend/issues/28)
